### ISSUE TITLE
failed to run because of flutter_gen

### ISSUE THREAD

**Issue by rrifafauzikomara** [phrase/flutter_sdk_example#14] opened 2023-05-04 14:48 UTC
Hi team, I can generated the phrase code by flutter_gen locally using `flutter pub run phrase`, so no error was found in my code.

code usage
```dart
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter_gen/gen_l10n/phrase_localizations.dart';

class LocalizationTest {
  const LocalizationTest({required this.context});

  final BuildContext context;

  AppLocalizations get tr => AppLocalizations.of(context);

  String getString(String key) {
    Locale currentLocale = Localizations.localeOf(context);
    String localeCode = Intl.canonicalizedLocale(currentLocale.toString());
    return Phrase.getText(localeCode, key) ?? key;
  }

  List<LocalizationsDelegate> get localizationsDelegates =>
      PhraseLocalizations.localizationsDelegates;

  List<Locale> get supportedLocales => PhraseLocalizations.supportedLocales;
}
```

l10n.yaml file
```yaml
# Where to find translation files
arb-dir: lib/localization/l10n
# Which translation is the default/template
template-arb-file: app_de.arb
# What to call generated dart files
output-localization-file: app_localizations.dart
output-dir: lib/localization/l10n/gen
synthetic-package: true
nullable-getter: false
```

in my local, the above code is not an error. But when I run the project, I got this error.
```dart
Error: Couldn't resolve the package 'flutter_gen' in 'package:flutter_gen/gen_l10n/app_localizations.dart'.
```

I know that `PhraseLocalizations` and `AppLocalizations` it's from flutter_gen, I saw ur example as well. But the diff is in your example can run the project but in my side cant, do I miss some setup?

**Comment by rrifafauzikomara** [comment] 2023-05-04 16:46
Update, on CI/CD i got this error as well.
```dart
 error • Target of URI doesn't exist: 'package:flutter_gen/gen_l10n/phrase_localizations.dart'
```

even though in locally not getting that error

**Comment by theSoenke** [comment] 2023-05-05 11:33
Hi @rrifafauzikomara, could you try setting `synthetic` to false and check whether this fixes the build error? It might be the same issue as mentioned here: https://github.com/phrase/flutter_sdk_example/issues/7

**Comment by rrifafauzikomara** [comment] 2023-05-05 19:20
Hi @theSoenke but I don't need it to generate the code for my project, I need it as a flutter_gen (cached)

<img width="940" alt="Screen Shot 2023-05-06 at 3 01 06 AM" src="https://user-images.githubusercontent.com/26451363/236558018-3ac086ca-a1eb-45b3-879b-c7590e08ad84.png">

Btw I add this phrase as a package/module, not a project. The reason is because in my project using modularization (have multi packages per feature).

for better visibility:

    # Root Project
    .
    ├── features               
    |   ├── feature A         
    |   ├── feature B
    |   └── feature etc
    |
    ├── lib                    
    |
    └── libraries
        ├── ep_localization
        └── libraries etc



If I use from generated one, I got this error.
```
Launching lib/launcher/main_prod.dart on iPhone 13 Pro in debug mode...
Running Xcode build...
Xcode build done.                                           47.1s
Failed to build iOS app
Error (Xcode): Invalid depfile: /Users/<my_user>/Downloads/<my_project>/.dart_tool/flutter_build/74bd82d182cebd1a02dbabb8fec264cf/kernel_snapshot.d

Could not build the application for the simulator.
Error launching application on iPhone 13 Pro.
```


before:
```dart
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter_gen/gen_l10n/phrase_localizations.dart';
```
after:
```dart
import 'package:ep_localization/localization/l10n/gen/app_localizations.dart';
import 'package:flutter_gen/gen_l10n/phrase_localizations.dart';
```

and if I use all from generated code, can run it, example:
```dart
import 'package:ep_localization/localization/l10n/gen/app_localizations.dart';
import 'package:ep_localization/localization/l10n/gen/phrase_localizations.dart';
```

but like I say before, i need it from flutter_gen, not from generated code for my project.

**Comment by rrifafauzikomara** [comment] 2023-05-12 14:11
hi @theSoenke , any update?

**Comment by theSoenke** [comment] 2023-05-16 09:43
Hi @rrifafauzikomara, sorry no update yet. But let me take a closer look how to handle this case

**Comment by rrifafauzikomara** [comment] 2023-05-16 19:01
Hi @theSoenke , thanks for ur help

**Comment by rrifafauzikomara** [comment] 2023-05-30 14:14
Hi @theSoenke any update?

**Comment by felixssimoes** [comment] 2023-06-09 10:04
@rrifafauzikomara Did you set generate to true in the pubspec.yaml file?
```yaml
flutter:
  uses-material-design: true
  generate: true # <-- this line
```

If not, please try to add it and then run `dart run phrase` to re-run the translations' files generator.

**Comment by rrifafauzikomara** [comment] 2023-06-17 18:12
@felixssimoes already did that before from [this](https://github.com/phrase/flutter_sdk_example/issues/14#issue-1696179005) setup but still not working

**Comment by rrifafauzikomara** [comment] 2023-07-11 20:50
Hi @theSoenke @felixssimoes any update?

**Comment by felixssimoes** [comment] 2023-07-24 07:31
@rrifafauzikomara How is your `pubspec.yml` file? Did you specify which version to use for the phrase package `phrase: ^2.0.0`?

I am running out of options here. I could reproduce the behavior you described here when either the `generate` was not set or the `phrase` package have no version set. If this is not your case, we're going to need more information about your setup in order to be able to help you.

**Comment by raphaelbarbosaqwerty** [comment] 2023-09-13 21:01
Hi! We had the same issue and we was able to fix it following these paths. 

`pubspec.yaml`
```yaml
...
dependencies:
  phrase: ^2.1.0
  ...
...
flutter:
  # generate: true
...
```

`l10n.yaml`
```yaml
arb-dir: lib/l10n/src
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false
```

The last two commands will generate the Phrase and AppLocalization files.
```
flutter clean && flutter pub get
flutter pub run build_runner build --delete-conflicting-outputs
flutter packages pub run build_runner build
flutter pub run phrase
flutter gen-l10n
```

Sometimes can be a cache problem activate and deactivate the intl will fix it or removing the `generate: true` from `pubspec.yaml`.

References:
https://github.com/dart-lang/build/issues/2835#issuecomment-921007367
https://github.com/dart-lang/build/issues/2835#issuecomment-697931824

**Comment by felixssimoes** [comment] 2023-09-18 09:09
I gave this issue another go but I still cannot reproduce the behavior described. Let me give you my view on how this should work when all goes well;

1. Assuming all is well configured, as described in this repo's readme file, when we run `flutter pub get` the localization files are generated automatically. This are `app_localizations.dart` and `app_localizations_<locale>.dart` (one for each supported translation). This is part of Flutters localization code generation and not, yet, phrase SDK.

2. Then when we run `dart run phrase` the file `phrase_localizations.dart` is generated. This should be all that's required to have this working.

If the first step is not working the case then something is not properly configured. You should probably refer to Flutter's official documentation to check what could the problem be.

If this step works correctly until you add phrase SDK then there could be some sort of incompatibility between your app setup and Phrase SDK. In this case we'll have to look into it with your app's setup to try to understand what could the problem be.

One thing I suggest you do is to try to troubleshoot is:
1. Try using Phrase's `flutter_sdk_example` and see if the translation files are generated. This should work out of the box, without any code changes, executing the 2 steps I mentioned in the beginning. If not this can point to something not properly setup in your system.
2. Try creating a new Flutter project and setup localization according to Flutter's documentation without using Phrase SDK. If this does not work then it definitely points to something not properly working in your system.
3. If both previous setups were successful but you still cannot build your main app with Phrase SDK, then try, step by step, to configure the test app, from previous step, with the same setup as the app that is not working. This should eventually stop working and then you'll have a better understanding of where the problem lies and maybe we can help you.

I really would like to be able to help but, as I said before, my hands are tied. If I cannot reproduce the behavior I cannot help you with the solution for it.

**Comment by felixssimoes** [comment] 2023-09-18 09:09
@raphaelbarbosaqwerty I tried to remove the `generate: true` from pubspec.yaml and run as you suggested. Doing so and then run `flutter gen-l10n` fails with the error `Attempted to generate localizations code without having the flutter: generate flag turned on.` when ran after `flutter clean`.

**Comment by raphaelbarbosaqwerty** [comment] 2023-09-18 16:34
Yes, that's the problem  @felixssimoes , is more related to the `gen-l10n`. I think we can close this PR is not related directly to `phrase sdk`, instead is related to the `flutter_gen`.

**Closed as completed** 2023-09-26 11:37 UTC
